name: Amazon Price Tracker

on:
  schedule:
    - cron: "0 4 * * *" # 9 AM Pakistan Time (UTC+5)
  workflow_dispatch:

jobs:
  track-price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tracker
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIEVER_EMAIL: ${{ secrets.RECIEVER_EMAIL }}
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: 587
        run: |
          python main.py
